name: Validation Action

on: 
  push

jobs:
  test:
    permissions: {}
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install Bun
        run: npm install --global bun
      
      - name: Install packages
        run: bun install

      - name: Run tests
        run: bun test

      - name: Upload results to Codecov
        uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
